### ISSUE TITLE
install fails on debian stretch

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#124]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.4.1
Node version: v8.11.4 (via nvm)
NPM version: 5.6.0 (default with this version of node)
Operating system: debian stretch (i386)
```

About the bug...

- Are you getting an error message?
    - Yes, the install fails
- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?
    - n/a
- Is the behavior different from expected?
    - Yes, install should be successful, but it is not.
- Can you provide steps to reproduce the issue?
    - Just try to install thumbsup globally, using `npm install -g thumbsup`

When installing dependencies of thumbsup, npm tries to install integer (as integer is a dependency of better-sqlite3, and better-sqlite3 is a dependency of thumbsup). The install fails as it tries to use node-gyp to build something. This build requires `make` and `g++` in order to build successfully.

After installing `make` and `g++` as debian packages, the npm install of thumbsup runs successfully.

It is a pain to require `make` and `g++` in order to install thumbsup. Is it possible to avoid it?

**Comment by oupala** [comment]
This seems related to #112.

**Comment by rprieto** [comment]
Hi. Thanks for raising this and posting your resolution details. Unfortunately these are requirements to build most Node.js applications that depend on native modules. I had a look at whether it would be possible to provide native platform binaries but it looks quite complex.

To avoid having to install any dependencies I recommend using the Docker image: https://thumbsup.github.io/docs/2-installation/docker/. Hopefully this works for your setup.

**Comment by oupala** [comment]
Installing `make` and `g++` should at least be mentioned in the documentation.

And unfortunately, there is no official docker support on i386 so I cannot use the docker image.

Is there a way to avoid using native module binaries? Do you think it is possible to use an alternative to `integer` so there is no need to build anything?

**Comment by oupala** [comment]
Maybe switching to the standard sqlite3 library would make thumbsup a little slower but a lot easier to install.

Looking at [integer issues](https://github.com/JoshuaWise/integer/issues), they're all related to installation problem. So is [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3/issues) which has some installation related issues.

Maybe thumbsup users can afford a little slower gallery generation to get thumbsup very easy to install (a real `npm install` and that's all folks!).

**Comment by rprieto** [comment]
Thanks, very good point I will mention `make` and `g++` in the docs :+1:

This is actually quite common in the Node ecosystem because packages tend to have a lot of transitive dependencies. Even if we removed `integer` it will be hard to ensure that we won't ever use (or one of our dependencies never starts using) another package with native bindings.

Thumbsup currently uses `better-sqlite3` because it's much faster than the other packages ([see the README](https://github.com/JoshuaWise/better-sqlite3)). I know of a few users with 50GB galleries or more, and at the time of implementation it made a significant difference. Happy to be proven wrong of course 🙂If you want to run a non-native test on a very large gallery I'll be happy to switch if the performance is reasonable.

I do agree that the current installation issues of `better-sqlite3` are not ideal, but if possible I'd rather help fix them - or maybe help the other libraries improve their performance.

**Comment by oupala** [comment]
Do you think it could be possible to use the standard sqlite3 library for a default install. And for those who needs strong performances, there is a flag to change in the config to allow to use the native better-sqlite3 library?

It could be a way to make thumbsup very easy to install for the average user, and make it very performing for power users. And I also think that using the docker image is not an option for the average user. Using docker is easy only for those who have understood a bunch of concepts about docker.

**Comment by rprieto** [comment]
Unfortunately that would be a big change because the libraries don't have the same interface. This would also be a very short-term fix, as I mentioned I can't keep an eye to prevent any native bindings from being used in the future. For now all I can do is update the docs with the install steps.

It's a shame there is no Docker support for i386. The Docker install is actually very simple, even for people have never used Docker. It's a single command that needs to be run: https://thumbsup.github.io/docs/2-installation/docker/.

**Comment by oupala** [comment]
Do you really think taht native bindings are unavoidables? The main flaws is in my opinion that you have to use two different package managers to install thumbsup: npm for thumbsup, and apt (or yum) for some build tools.

Concerning docker usage, I agree that using docker is pretty straight forward. But before using it, you have to understand it, how it works, what is an image, a container, how to use volumes, how to manage networks. And that is not really simple for an average user who just want to generate an image gallery.

**Comment by oupala** [comment]
I'm using node-sass in a project, and I can see that the npm install downloads the binary:

```npm
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/user/dev/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/user/.npm/node-sass/4.9.3/linux-x64-57_binding.node
```

This could be solution for native bindings.

**Comment by rprieto** [comment]
Thanks, yes that could be an option. You'd have to raise that on the `better-sqlite3` project, if they can release versioned Windows/Unix/macOS bindings, including Alpine Linux which is the base for the Thumbsup Docker image.

For Docker I don't understand what you mean. For me:
- A new user can simply copy-paste the single command from the Thumbsup documentation. There is no need to understand concepts like Docker networking which is irrelevant here.
- Thumbsup is a command-line tool which requires other binaries like `ffmpeg` and `exiftool`. This means it's already targeted for a certain type of users. There are other projects that will be better suited in some cases.

Unfortunately there are other missing features that are more important at the moment, so it's very unlikely I change how it's installed or packaged.

**Comment by oupala** [comment]
I added an issue in [integer repository](/JoshuaWise/integer/issues/8) (which is a better place than better-sqlite3).

I just meant that docker is not *that* easy to install and use, in a general way. You should ask an average user to install and user docker to see how hard it is for an **average** user (note the **bold**) to make it work.

But I think we could stop this discussion here, as I think we have shared our vision and the conclusion is:

> There are other missing features that are more important at the moment, so it's very unlikely I change how it's installed or packaged.

By the way, I find thumbup is a very great peace of code!
