### ISSUE TITLE
Ability to configure video transcoding (format, bitrate...)

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#130]
## Feature request

thumbsup transcodes videos to mp4.

It would be cool if there is a way to configure the output format.

We might prefer webm instead of mp4.

**Comment by rprieto** [comment]
This is a good idea :+1: Please feel free to create a pull-request in https://github.com/thumbsup/downsize. It should just be a matter of

- adding a new option like `{ format: 'webp' }`
- changing the `-f mp4` flag in https://github.com/thumbsup/downsize/blob/master/lib/index.js accordingly

Otherwise I'll try to get to it after the current features.

**Comment by rprieto** [comment]
Looking at #103, ideally we should be able to configure the bitrate or resolution too.

**Comment by oupala** [comment]
I've created a first pull request ([downsize#7](thumbsup/downsize/pull/7).

Tell me what could be improved on it (parameters, tests).

We should also add AV1 in a near future. AV1 is the next generation video codec that might conquer the web.

I can try to add bitrate and resolution once format seems ok. It'll be a way for me to understand how all this work.

**Comment by rprieto** [comment]
Thanks @oupala for your help on https://github.com/thumbsup/downsize ! Thumbsup `2.6.0` is now out with the new `--video-format`, `--video-quality` and `--video-bitrate` options.
