### ISSUE TITLE
Social comments plugin

### ISSUE THREAD

**Issue by thanhtunguet** [thumbsup/thumbsup#136]
Hello,

Although this package is for static album websites, I think every album page has comment section will be great. To be able to deploy on static servers, this product may use social comments plugin from social networks. For example: Facebook.

Can this idea come true?
Thanks!

**Comment by rprieto** [comment]
Hi, that's a good idea! I can think of two ways to add social comments:

- next to each image, in the light box. This would use a LightGallery plug-in like http://sachinchoolur.github.io/lightGallery/demos/comment-box.html
- on the album pages, for example with a small Disqus code snippet at the bottom of the page.

Both would have to be added and configured inside a particular theme. They should just be a few lines of code, so that's easy.

- fork one of the themes, like https://github.com/thumbsup/theme-cards
- add the LightGallery plugin or the comments section in `album.hbs`
- use your forked theme using `--theme-path`

It would be really nice to make it an option when using the existing themes, but there is no "theme option mechanism" yet. I'll add another issue to start tracking this.

**Comment by thanhtunguet** [comment]
> Hi, that's a good idea! I can think of two ways to add social comments:
> 
> * next to each image, in the light box. This would use a LightGallery plug-in like http://sachinchoolur.github.io/lightGallery/demos/comment-box.html
> * on the album pages, for example with a small Disqus code snippet at the bottom of the page.
> 
> Both would have to be added and configured inside a particular theme. They should just be a few lines of code, so that's easy.
> 
> * fork one of the themes, like https://github.com/thumbsup/theme-cards
> * add the LightGallery plugin or the comments section in [album.hbs](https://github.com/thumbsup/theme-cards/blob/master/theme/album.hbs)
> * use your forked theme using `--theme-path`
> 
> It would be really nice to make it an option when using the existing themes, but there is no "theme option mechanism" yet. I'll add another issue to start tracking this.

I've tried to add comment box according to your guide. It works well. But I think comment box should be global option instead of option for each theme.

Because Facebook comment plugin treats each url as an object for commenting, this feature requires a global option (Let me name it "**origin-url**") to create absolute HTTP url for individual image. (Facebook does not allow url in file:/// protocol).

**Comment by rprieto** [comment]
Hi, about the global option, how would it be used? It is a simple value that the themes can render in the HTML like this?

```html
<div class="fb-comments" data-href="{{ gallery.originUrl }}/{{ album.url }}"></div>
```

**Comment by rprieto** [comment]
Themes now support options. This can be solved if the theme that renders the comments box also  supports a `baseUrl` option.
