### ISSUE TITLE
Multiple input folders

### ISSUE THREAD

**Issue by xtavras** [thumbsup/thumbsup#141]
## Feature request

Provide multiple input folders for one output. For example my photos are located in "media/photos", I don't import whole folder, but just two folders like "media/photos/2017" and "media/photos/2018".

At the moment the last one command with "--input media/photos/2018" with the same output folder overwrite photos from "2017" folder. 

As workaround I can define different output folders and create index.html by myself with the links to each folders. But maybe built-in options would be very helpful.

**Comment by rprieto** [comment]
Hi. This is an interesting idea. Unfortunately it would be hard to implement without major changes in the indexing engine & database, because they only store relative paths. Relative paths are used so you can run thumbsup from multiple computers mounting the same server share, or on a USB drives that changes mount point every time. We would have to keep some sort of "named" input folder mapping, like `--input holidays:/mnt/holidays --input misc:/data/photos`.

To keep it simple, what about allowing custom include/exclude patterns like the [AWS S3 CLI](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html) or [RClone](https://rclone.org/filtering/)? It could look like `--include "2018" --exclude "Holidays"` (exact wildcard pattern syntax to be defined).

**Comment by xtavras** [comment]
Hi @rprieto

yes, `--exclude` option sounds great. Btw, on a side note, when do you plan to build new release with features from https://github.com/thumbsup/thumbsup/issues/128 ?

Thanks for your project :+1: 
Stan

**Comment by rprieto** [comment]
Version `2.7.0` is now out with the `--include/exclude` flags as well as the ones from #128. They're all documented on https://thumbsup.github.io/docs/3-configuration/input-settings/

Let me know if it helps!
