### ISSUE TITLE
Image size in theme templates

### ISSUE THREAD

**Issue by Roliga** [thumbsup/thumbsup#149]
## Feature request

Hey, first of all thanks to everyone working on this project!

I wanted to make a theme based on [PhotoSwipe](https://photoswipe.com/) but it requires the size of images to be known in advance, so while the album pages are being generated. As far as I can tell there's no way to do this at the moment, maybe it's something that can be added?

**Comment by rprieto** [comment]
Hi, glad you like it! You're right that's not possible right now, but it's only a few lines of code away - then you would have access to something like `file.meta.width / height` in the templates.

If you're keen to make a pull request, you'd have to read the values from the EXIF object in `metadata.js`. Otherwise I'll try to look at it next.

**Comment by rprieto** [comment]
Hi @Roliga, this is now implemented. Version `2.9.0` exposes `file.meta.width` and `height`.
