### ISSUE TITLE
How to add to an existing gallery?

### ISSUE THREAD

**Issue by hupfdule** [thumbsup/thumbsup#207]
Running as a Docker container:

```
Thumbsup image tag: 2.14.0
Operating system: Debian Buster
```

Suppose I have the following directory structure:

```
/path/to/photos/dir1
/path/to/photos/dir2
/path/to/photos/dir3
/path/to/photos/dir4
/path/to/photos/dir5
```

and I want to put dir2 and dir4 into two albums of a new gallery, I can run

```
docker -t -v /path/to/photos/:/input:ro -v /path/to/gallery/:/output thumbsupgallery:thumbsup:2.14.0 thumbsup -i /input --include dir2 --include dir4 --output /output --albums-from "Travels/%path"
```

to have both in the gallery as subalbums of "Travel".

Now, when I want to add a new "dir6" as a new subalbum below "Travel" and I issue the same command as above but with the `--include` directives replaced by `--include dir6` I end up with a single album "Travel/dir6" and the others have vanished (even though the files exist, they are not referenced by the HTML anymore).

So what it the correct approach to handle additions to a gallery?

Do I need to reference all the existing albums again in the command?

How to handle this situation if I then want to include photos from a different input directory, like `/some/other/path/for/fotos`. Can this be achieved anyhow?

And how to handle multiple top-level albums to achieve an album structure like

```
Travels/dir2
Travels/dir4
Travels/dir6
Work/dir1
Work/dir3
```

Is this possible? And if so, how?

**Comment by rprieto** [comment]
Hi @hupfdule.

The role of `--include` is do do fine grained filtering on the `--input` folder. Any file that doesn't match will be excluded. With that in mind:

- Yes you would have to re-specify all the previous folders, otherwise the next run will only keep the new include pattern
- In any case, the entire `--input` folder is being scanned every time. I really wouldn't recommend scanning a very large folder (e.g. `/home`) to only include a few files

Thumbsup is really made to work with a *single* input folder which contains all the photos you want to process. You cannot specify 2 input folders. There are some ways around it however:

1. Create a top-level "input" folder and move all source folders there
2. Create a top-level "input" folder, in which you create symlinks to the different source folders
3. Use the Docker version, and mount the relevant input folders into the same area

Option 2 might be a good solution in your case.

**Comment by kecskemethy** [comment]
I have a similar issue. I've generated my s3 based thumbsup image gallery in my home server. It has hundreds of folders.
But this is the only location where I have all the original images - in one place - so I can update my site from there only.

It would be nice if I could add any new folders from a different computer - e.g from my laptop - without having all the additional old images there.

What I mean here it would be nice to able to generate a new sub-folder gallery in a different computer and allow us to upload that into the big album an make it merge there somehow. e.g. when we use an --incremental option which would allow us to generate a specific new sub-folder in an existing album which would be automatically picked up if present... OR it would be inserted into an existing album's structure which we would need to provide. (maybe not the full structure but only the htmls)

**Comment by rprieto** [comment]
Hi, thanks for sharing this use case. I see how it would be very useful, however I can't think of a way to implement it.

Thumbsup keeps a local database of all files & metadata (thumbsup.db) which it uses to generate the HTML pages. If you run it from 2 locations that don't share a database, then each one will create a different page structure which will be impossible to merge.

The simplest way might be two generate two galleries, and maintain a top-level page that links to both. If you style it like the actual theme it could be seamless.

**Comment by rprieto** [comment]
Hi, I'm closing this issue for now as I can't think of a way to implement this. The challenge is that the database is very central to how thumbsup works, and there is a strong mapping between 1 input = 1 database = 1 gallery.

Thanks again for raising these use cases and hopefully some other solutions become possible in the future. In the meantime generating multiple galleries might be the best solution.
