### ISSUE TITLE
[Feature Request] Add option to specify a different location for thumbsup.db

### ISSUE THREAD

**Issue by gnafuthegreat** [thumbsup/thumbsup#216]
I've just started using thumbsup, and I love it so far!  I've learned a lot from the documentation.

## Feature request

I'd like to be able to specify a different location for thumbsup.db and thumbsup.log than the base of the gallery.  For example, I like to have my config.json and local installation of thumbsup in a project folder, my pictures in another folder, and the generated gallery in public_html.  I would prefer not to have thumbsup.db or thumbsup.log in the published web folder but rather in the project folder alongside my config.json settings.

Apologies if that's something you've already considered, or if I missed an existing setting.

**Comment by rprieto** [comment]
Hi @gnafuthegreat, that makes a lot of sense.

I chose the output folder by default so that thumbsup could be executed from anywhere. It also made sense because the current folder might have a few JSON config files, but 2 galleries never share the same output folder.

However I completely get your use case. Do you think a flag like `--database-path` makes sense? I'm thinking it would be the full path to the database (filename included), either absolute or relative to CWD. The log file would just be written next to the database unless there's a good reason to have 2 different arguments.

**Comment by gnafuthegreat** [comment]
That works for me, though I could see some folks wanting to specify a separate location for the log as well with something like `--log-path` or `--log-file` (I don't care one way or the other).
