### ISSUE TITLE
Album download

### ISSUE THREAD

**Issue by VictorLamoine** [thumbsup/thumbsup#249]
I would like a button to be able to download all the pictures in an album:
- Each individual file
- Or a zip

From my understanding this would require Javascript or PHP (zip) so this should be optional.

**Comment by rprieto** [comment]
Hi, you can use `--album-zip-files true` to automatically generate a ZIP file per album. The built-in themes show a link towards the bottom of the page, or you can customize this with your own theme.

It requires the `zip` binary in your path (and will give an error otherwise). There is no server-side language needed, the ZIP files are generated at build-time.

**Comment by VictorLamoine** [comment]
I did not see this option, it works great thanks!
