### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#367]
## Bug description

```
Unexpected error The module '/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 111. This version of Node.js requires
NODE_MODULE_VERSION 127. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

## Steps to reproduce

install all the dependencies on WSL2 under Windows 11 including ImageMagick with heic support
then install thumbsup
my commandline was `thumbsup --input /mnt/d/mypage/lightgallery --output ./pics`
my version of node is v22.2.0

**Comment by rprieto** [comment]
Hi, this message typically happens if you upgrade Node after installing thumbsup. That's because binary modules (e.g. sqlite) are compiled for a specific version.

You can try un/re-installing thumbsup, or running ˋnpm rebuild thumbsup` as suggested (using ˋ-g` if that's how you installed thumbsup). Neither will affect your galleries.

**Comment by inhahe** [comment]
Ah, I thought that might have been the problem, I did try reinstalling it, that didn't help, but npm rebuild thumbsup seemed to do it. what's -g do?

**Comment by rprieto** [comment]
`npm install ...` downloads a package in the current folder where you have a `package.json` file. It allows you to have multiple copies/versions in different folders.

`npm install -g ...` installs a package globally in your system, and puts the executable in your PATH (if any).

`npm rebuild` has the same `-g` flag.

Since it's solved I'm closing the issue.
