### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by dkebler** [thumbsup/thumbsup#57]
enhancement -

Add loading of custom.css after all others in the head.  Do not overwrite this file when building the gallery.  As it stands viewer.css is overwritten when building and is loaded before lightgallery.css.

I'm working on a pr for this.

**Comment by rprieto** [comment]
Currently, all custom CSS (`--css`) is added to `style.css`. Would it be enough to load that as the last CSS file?

**Comment by rprieto** [comment]
Only downside is that it won't allow overriding LESS variables used by the different themes. Unless you can think of something?

**Comment by dkebler** [comment]
I saw the option after I made this issue.  I didn't know where it got loaded.  Moving the style.css would not work since when the site gets rebuilt it gets written over by the copy in repo's public/.  I just added a "custom.css" line to the end of the list of css in your albums template.  That works fine and never gets written over. `<link rel="stylesheet" href="{{relative 'public/custom.css'}}" />`  Then user just adds their own custom.css file to public/

I use Hugo and in my go templates for hugo I can conditionally add a  custom.css load line if a parameter is set (like using custom css).  Handlebars probably has something similar.  Then --css could simply turn on/off that line.

As to your compiled less I couldn't find your processing code in src/ so no sure where you are putting the corresponding css (in the body?).  I would dump the css file in public/ as theme.css and then add it just before custom.css in albums.hbs

**Comment by rprieto** [comment]
This is the code in [website.js](https://github.com/thumbsup/node-thumbsup/blob/master/src/output-website/website.js) that renders the CSS:

```
function renderStyles(callback) {
    var themeFile = path.join(DIR_TEMPLATES, 'themes', opts.theme, 'theme.less');
    var themeLess = fs.readFileSync(themeFile, 'utf-8');
    if (opts.css) {
      themeLess += '\n' + fs.readFileSync(opts.css, 'utf-8');
    }
    less.render(themeLess, function (err, output) {
      if (err) return callback(err);
      var dest = path.join(opts.output, 'public', 'style.css');
      fs.writeFile(dest, output.css, callback);
    });
  }
```

This means any custom LESS gets appended to the theme's LESS, and built into `style.css`. However you're right, it doesn't actually let you override [theme variables](https://github.com/thumbsup/node-thumbsup/blob/master/templates/themes/cards/theme.less) since it's added at the end of the file (too late to change them).

With what you suggested, I can think of 4 options:

1. keep `--css` that appends an external file to the theme, but move the resulting `styles.css` to be the last one in `<head>`. This would solve the immediate problem: any custom CSS would be loaded at the end and have precedence over other code
2. change `--css` to write to `custom.css` instead of `style.css`, and load that new file at the end. In this case the user doesn't have to copy anything because the file is generated. Keep `style.css` as it is, maybe renamed to `theme.css`.
3. change `--css` to toggle an additional `<link>`, and the user has to ensure that this file exists, either copying it manually in `/public` or pointing to a CDN. This is similar to (2) but thumbsup doesn't actually read that file, it merely points to it. I'd rename that option to `--external-css`.
4. if we choose options (2) or (3), we can also introduce `--theme-variables` that gets *prepended* to `style.css` and let people override theme variables

Thoughts?

**Comment by rprieto** [comment]
@dkebler latest master now loads any custom CSS at the end. Can you try adding `--css path/to/custom.css` see if it fixes your problem? I did some testing and can easily override styles from both the theme and lightgallery for example.

**Comment by dkebler** [comment]
@rprieto Since I have been manually incorporating your .html file this is no longer an issue for me.

If/when the data model export is working this will all be moot as well as I already have the html templates and css I need for my project.  

So...I haven't had a chance to try this and confirm it's working.
