### ISSUE TITLE
Corrupt images prevent the gallery from being generated

### ISSUE THREAD

**Issue by tribut** [thumbsup/thumbsup#75]
## Bug report

```
Thumbsup version: 2.1.0
Node version: 6.11.4
NPM version: 3.10.10
Operating system: Debian Stretch
```
When graphicsmagick cannot read a file, an error is thrown and the gallery is not generated. I would have expected the image to be skipped:

~~~~
Finding media       [=========================] 53653/53653 done
Updating database   [=========================] up to date
Processing photos   [=------------------------] 2395/103218 (493min left)Unexpected error
{ Error: Command failed: gm identify: Bogus DQT index 9 (/srv/files/Bilder/0000/Handybilder/2010-02/14022010037.jpg).
gm identify: Request did not return an image.

    at ChildProcess.onExit (/home/www-bilder/.local/lib/node_modules/thumbsup/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) code: 1, signal: null }

~~~~

**Comment by rprieto** [comment]
I can see how stopping the whole process when there's an error can be annoying, for example when processing 50,000 photos overnight.

If we skip errors instead, we'll have to solve a few questions:
- how do we report the list of images/photos that have errors? I don't think it's practical to print them in the output as it could be a long list. Maybe something in the final summary that says `Warning: 3 input files were skipped because of errors (see thumbsup.log)`?
- do we simply skip the preview generation (replace the preview with a placeholder), or do we remove them completely from the final galleries?

**Comment by tribut** [comment]
Yes, having the error reported at the end in some way would be helpful.
I have no strong feelings whether a placeholder should be used or the images should simply be skipped. The latter could be considered the more surprising outcome so me UX training says using a placeholder is probably better. But this should be an extremely rare occurrence, so...

**Comment by rprieto** [comment]
Sounds great. Using a placeholder is a lot easier than retro-actively changing the data model during the thumbnail generation. I'll try to have a look soon!

**Comment by rprieto** [comment]
Hi, the latest code on master skips all problematic files and prints a warning at the end if any files were skipped. The log file contains all errors for troubleshooting.

For now it doesn’t create a placeholder, so the HTML page will have the browser default “broken image” icon.

Thanks for the bug report and the ideas @tribut!
