### ISSUE TITLE
Feature:adding a sidepanel with exif information

### ISSUE THREAD

**Issue by eephyne** [thumbsup/thumbsup#80]
I just saw that some file have the camera name at the bottom, could it be improve with a sidepane containing a bunch of exif information and why not a minimap showing gps coordinates.

Lets go further again, why not a link in the homepage showing a map with all the photo pinned on it ? (like we can found on piwigo).
But I don't know if this is doable with static website, mainly on big big pictures database.

I can help at my level if you need any help

**Comment by rprieto** [comment]
These are all great ideas! From a quick think:

**Side panel with exif info and map**

That sounds pretty easy. I'm about to push a change that creates re-usable templates that the different themes can include. It would be nice to have `exif` and `map` templates. Then we can work on including them in one of the themes - or maybe creating a new theme.

I'm not familiar with Piwigo, but Synology Photo Station is also nice for inspiration: 

![Synology Photo Station](https://i.hinnavaatlus.ee/ext/89e0087e859260cd602e51f83bc9570a9050aa0c/687474703a2f2f692e696d6775722e636f6d2f424935744d416a2e706e67/).

**Global map of all photos**

That would be awesome, but probably much harder. The tough part will be to avoid pinning 20,000 photos on the map. For example on iOS as you zoom in & out it groups photos from similar locations into a single square, so you only ever have ~3 groups on screen at any time. Please share if you have some ideas on how to do that.

**Comment by rprieto** [comment]
http://leafletjs.com/ looks very easy to use, and doesn't seem to require API Keys like Google Maps.

**Comment by eephyne** [comment]
For global map if we simply record every files with gps info in a file with their gps info.
like that 
`folder1/subfolder/filename GPS_LAT GPS_LON`
I made a test with 20000 lines I got 1.7Mb which is pretty big. Maybe compressing it before sending since there will be a lot a redondancy (mainly in filename).
For the parsing part I have absolutely no idea how it would be.

~~Another idea could be to use dynamic splitting.
Imagine we got 20000 entries but of course everything is not equally distanced on the global map, surely 90-95% will be at the same range of 5 or 10km.
So we take a progressive range to get about 100 entry max per files, then we generate the map loading function to load only the files need to be showed.~~

we could also use a folder system.
each subfolder is a 1/100 of the parent folder so each folder have 100 subfolder for a 10x10 square and so on.
This system could easily resolve the issue of loading only a bunch of data if we zoom out or take only the portion needed if we zoom in.
but I don't know how the static generation could use a folder system

**Comment by rprieto** [comment]
Thanks! Getting the data should be easy, as it should already be in the thumbsup index (`metadata.json` in 2.1.0 and before, `thumbsup.db` from 2.2.0 onwards).

One easy option to start with could be something less dynamic, simply based on the city the photos were taken in. So regardless of how much you zoom, you would see 1 "block" per city that says something like "159 photos". Then you can click to be taken to that group of photos. What do you think?

**Comment by eephyne** [comment]
I wasn't imagine a folder by town/sector at first, symply a link to the photo, but a link by sector is a nice idea.
But like I said earlier we risk to have a large amount of photos for some sectors

**Comment by rprieto** [comment]
One nice thing about thumbup Albums is that they don't have to map to any folder structures. An album can contain arbitrary images, and an image could even belong to several albums. We just need a criteria to group them, so it could be:

```js
file => 'cities/' + file.meta.city
// or
file => 'countries/' + file.meta.country + ' /cities/' + file.meta.city
```

The `meta.city/country` properties only exists on a branch for now but hopefully I can merge it soon.

**Comment by eephyne** [comment]
I assume the meta.city properties make request for every picture on a website ?
making a large amount a request is not a problem ?

**Comment by rprieto** [comment]
The code I have locally bundles a small geolocation database file. It can resolve 10,000 photos (lat, long) in less than a second, so for now it's done on startup. Eventually it could be done in the indexing phase, so the results can be saved and cached in `thumbsup.db`.

The only thing is that it returns the closest city based on the "town centre" coordinates. So if a photo is taken on the edge of a city, it might return the next suburb. Should still be good enough for grouping photos IMHO.

**Comment by eephyne** [comment]
Yes I also think that would make a very nice addition.

**Comment by rprieto** [comment]
Are you OK if I split this into 3 issues: EXIF side panel, mini map, and global photo map?

**Comment by eephyne** [comment]
yes no problem

**Comment by amcolash** [comment]
I accidentally posted the below into #81, here it is though. Most of it still applies to some extent to the maps.

So I have started looking into the potential steps needed to take on this feature. It is quite a lot of work but I am not necessarily volunteering to do it, just documenting but I might look into it if I have time in the future.

- Exif info is missing from the final resized images for some reason, need to investigate the downsizer that wraps graphicsmagick.
- The current lightgallery package being used does not have an Exif viewer, so a new plugin would have to be made for it.
- The three themes would need to be updated.
- All builds need to be run (docker, main version, etc)

This could turn out to be a pretty big undertaking and by the end many pull requests. I wanted to document my findings for now though so I don't forget and others know.

Additionally another option would be to embed the exif info into tags on the generated html, I do like that approach instead of grabbing from files but regardless lots of work ahead.

**Comment by amcolash** [comment]
Just another update based on some more research and information that I have found.

Currently, resizing images with graphicsmagick (using the node wrapper) strips exif information. This is not good if we want to keep that information embedded in the files which is preferable in case someone downloading those files wants that original information.

I tried using gm on it's own (without the node wrapper) and it appears that a resize will preserve the exif information. This leads me to believe that there is something that is missing from their docs as I was unable to copy said exif info when wrapped in node.

Next I tried to resize with gm + read / write the original exif data using exiftool. This got most of the exif info into the resized image but lost some of the more specific exif info that is unique to different cameras / manufacturers.

Finally, I thought "what if we use something other than gm?". This led me to finding [sharp](https://github.com/lovell/sharp). This is an extremely performant node library which has all kinds of image modification functionality. This library was able to save _all_ exif data in a resized version of my test photo at > 3x the speed (based on my limited testing).

I did not look deeply if this would be a complete drop-in replacement but it sure seems like switching downsizing from gm &rightarrow; sharp may be the best bet for quicker library builds + exif data preservation.

Since some users may not want that exif information shared outside of their original images, there should be an option to use exif info - which would also toggle the usage of the exif panel in lightgallery.

I would love comments at this point. I will begin looking into plugins for lightgallery and building an exif panel since this does not require any design decisions.

**Comment by amcolash** [comment]
Even more updates... Well, I started playing around with things and it turns out getting that exif data into everything was a piece of cake! Making it look pretty, having the fields that people want, making a plugin repo and other parts will be another issue.

Here is a little teaser - looks like I am going to do at least part of this after all ;)

![ezgif-5-9ac1cc2abb](https://user-images.githubusercontent.com/8282413/44447905-93546e80-a59e-11e8-8fc6-f0802a921ec5.gif)

**Comment by rprieto** [comment]
Hi, thanks for looking into this in so much detail! Here's a few thoughts:

### EXIF data

The screenshot above looks great!

You're right, for the moment it is removed from the final images, mostly for security reasons (just like Facebook, Twitter, Imgur, etc...). For example people might not want to publish the exact location of every photo on the internet. However if we add an EXIF panel then it could make sense to keep it since the info will be there anyway. I would put that behind a new flag like `--preserve-exif`.

However, all the EXIF data is kept in the thumbsup database, and also in the data model that's passed to the themes. The themes can access it in Handlebars using `<div>Caption: {{ file.meta.caption }}</div>.`.

How did you get access to the data in the example above?

### About the plugin / themes

Good point about the theme needing changes. To add some context, I have recently extracted the themes so people can create new themes, be creative, and not even use Lightgallery if they want something else. It raises two things:
- whether all 3 official themes should have the EXIF panel
- where the EXIF panel is implemented
  - I really like your idea of a LightGallery plugin. Then any theme using LightGallery can use that plugin if it wants to
  - otherwise it could be a shared Handlebars partials, but it probably will be tricky to implement a partial that works for everyone, since we don't know what themes will look like

I'm thrilled that you're keen to be involved!

**Comment by amcolash** [comment]
I love open source and selfishly want this feature for my own personal gallery. Since I liked the relatively simple setup of the project and extensiblity via themes I am more than happy to help out!

Let's see, so for the exif data I am actually grabbing that from the thumbnail jpegs (since they are loaded on page load) and then using the libraries [exif-js](https://github.com/exif-js/exif-js) to read the data and then [exif-date](https://github.com/blakeembrey/exif-date) for parsing the very odd exif date that is used by default.

I think using the exif data from the db could possibly be easier - I just haven't looked into that approach yet. The good thing is that my plugin just takes in a data object and generates the available fields. We could embed the exif info into `data` fields of each thumbnail (or similar). It would make it only useful for people using thumbsup however and less extensible for people outside of the ecosystem.

I am willing to do a bunch of forks + pull requests but at least for the themes it is a few lines of code for the plugin in the current state, which could be consolidated (merging the libraries into one final file).
```
<link rel="stylesheet" href="public/lightgallery/css/lg-exif.css" />
...
<script src="public/lightgallery/js/exif.js"></script>
<script src="public/lightgallery/js/exif-date.js"></script>
<script src="public/lightgallery/js/lg-exif.js"></script>
...
$("#media").lightGallery({
    ...
    exif: [true/false],
```

As for next steps for me, I am going to build out toggling functionality for the panel now that I have a base set for things. Additionally, I am going to look into consolidating things together and packaging up the plugin into it's own repo so that I am not just hacking on code unversioned.

I would love some thoughts on if grabbing exif from the images seems like a good plan or if you would want to embed that info into the page elements itself. I am not too tied to either method but would prefer to package it in such a way that users without thumbsup can still use the plugin. Maybe a hybrid mix?

P.S. sorry about all of the long comments, always easier to be verbose!

**Comment by amcolash** [comment]
Update from tonight and my hacking around, now the panel can be hidden. I will make a repo soon, pulling code out is always a bit of a pain ;) This all was much easier than I was expecting - which is great!

![peek 2018-08-22 23-56](https://user-images.githubusercontent.com/8282413/44509690-3e305f80-a667-11e8-8c2a-a6378f1003bb.gif)

**Comment by amcolash** [comment]
So I made a repo tonight with my changes pulled out best as I could. The 2nd image in the gallery has some GPS info so I added in the map panel too (that was almost too easy) and should be all that is needed for #81.

The only question now is for me to decide how I want to package things up since I have now 2 extra libraries (exif-js + leaflet) floating around and would like to make a "build" with all of the stuff together if possible.

Anyways, here is the repo that has a link to a demo you can try out: https://amcolash.github.io/lg-exif/.

![image](https://user-images.githubusercontent.com/8282413/44625918-1db31000-a8c8-11e8-9d7e-f4841002947a.png)

Time for bed!

**Comment by amcolash** [comment]
Bump. I think most of the pieces are in place at this point. Can you take a look @rprieto when you get a chance?

**Comment by rprieto** [comment]
Hi, thanks for the bump I'll have another look.

One aspect I'm not sure about yet is the fact that the side panel only works if the resized images have EXIF data. 

- On the plus side, it's a very generic solution where we can use any EXIF viewer.
- On the other hand, the EXIF info is already available in the data model that's passed to the template. For a concrete example I would like to have the side panel & map on my personal gallery but would hate to have to rebuild all 100GB of images. 
- This solution of reading the file in the browser would also limit us to photos, whereas videos also have their metadata available in the model (camera type, exact date, location...).

One approach could be to have a `--preserve-exif`, which is always useful even outside of the side panel.

Then some themes could have a basic side panel based on the metadata, and some could read the file. The power of themes is that everyone can do what they want :smile:

**Comment by amcolash** [comment]
I deliberately went down the path of not relying on thumbsup for the initial plugin so that other users of light gallery can use the plugin without needing to be inside of the thumbsup environment. I do agree that a complete re-gen of the gallery would be a huge inconvenience, so I will make a branch that is specific for thumbsup (and then keep parity between the two). I can work on this in the coming days when I get time for it.

Thanks for the suggestions. I was hesitant of embedding the info directly into the page markdown as it is _slightly_ harder to have a bot scrape the gallery pages for info, though that is the user job to care about such info being injected - which is why we have an opt-in flag. As long as a user can download the original images (which I think was a different pr/issue in progress), I am ok with this route.

**Comment by amcolash** [comment]
Alright, I made the plugin compatible with the embedded data attributes and falls back to exif info if there are not data attributes. I will just need to update the theme generation to handle this and I think most of this should be set to go.

**Comment by rprieto** [comment]
Thanks I really appreciate all your work on this. The system of trying to read both EXIF + data attributes sounds great to me! I'll add some comments on #133 to help finalise it.

**Comment by amcolash** [comment]
Looks like all of the building blocks are done for this issue. I think it is time to close it up 😁

**Comment by rprieto** [comment]
Indeed, and not a small feature! I'll release a new version tomorrow 🚀
