### ISSUE TITLE
Feature: add a small map in EXIF side pannel

### ISSUE THREAD

**Issue by rprieto** [thumbsup/thumbsup#81]
Will be implemented after #80.

- Could use http://leafletjs.com
- Could look like:

![PhotoStation map](https://camo.githubusercontent.com/9f6554946632aa21d1f769f0f9bd16e1cfed02e9/68747470733a2f2f692e68696e6e61766161746c75732e65652f6578742f383965303038376538353932363063643630326535316638336263393537306139303530616130632f3638373437343730336132663266363932653639366436373735373232653633366636643266343234393335373434643431366132653730366536372f)

**Comment by amcolash** [comment]
So I have started looking into the potential steps needed to take on this feature. It is quite a lot of work but I am not necessarily volunteering to do it, just documenting  but I might look into it if I have time in the future.

- Exif info is missing from the final resized images for some reason, need to investigate the downsizer that wraps graphicsmagick.
- The current lightgallery package being used does not have an Exif viewer, so a new plugin would have to be made for it.
- The three themes would need to be updated.
- All builds need to be run (docker, main version, etc)

This could turn out to be a pretty big undertaking and by the end many pull requests. I wanted to document my findings for now though so I don't forget and others know.

Additionally another option would be to embed the exif info into tags on the generated html, I do like that approach instead of grabbing from files but regardless lots of work ahead.

**Comment by rprieto** [comment]
Hi @amcolash , thanks for documenting this! Lots of good points. I think your comment might relate more to #80 (EXIF sidepanel), since this issue is specifically about displaying a map. Do you mind re-posting it over there? There's a few ideas I'd like to add to yours.

**Comment by amcolash** [comment]
Oh no, I am sorry I posted all of this to the wrong place! Most of this still applies, since we need exif, and most likely a plugin still. I will re-post there.

**Comment by rprieto** [comment]
@amcolash are you OK if I clean up this issue since you re-posted on the other thread?

**Comment by amcolash** [comment]
This feature should be set to be closed out due to #133.
