### ISSUE TITLE
doesn't seem to compile on raspberrypi

### ISSUE THREAD

**Issue by msharp1** [thumbsup/thumbsup#90]
I have this error when installing thumbsup on my RPI:
It is regular raspian stretch and npm using nvm

```
$ npm  install -g thumbsup
/home/pi/.nvm/versions/node/v9.5.0/bin/thumbsup -> /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/bin/thumbsup.js

> integer@1.0.3 install /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/integer
> node tools/install

make: Entering directory '/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node
  COPY Release/integer.node
make: Leaving directory '/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/integer/build'

> better-sqlite3@4.1.0 install /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/better-sqlite3
> node deps/install

==> cwd: /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/better-sqlite3
==> /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/lzz-gyp/lzz-compiled/linux -hx hpp -sx cpp -k BETTER_SQLITE3 -d -hl -sl -e ./src/better_sqlite3.lzz
/bin/sh: 1: /home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/lzz-gyp/lzz-compiled/linux: Exec format error
Error: exit code 2
    at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/thumbsup/node_modules/lzz-gyp/lib/exec.js:19:12)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@4.1.0 install: `node deps/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by rprieto** [comment]
Hi @msharp1, thanks for raising this and opening an issue with https://github.com/JoshuaWise/better-sqlite3. Did `LZZ_COMPAT=1` fix it for you?

I'm keen to use this package if possible since its synchronous API seems a lot faster than https://www.npmjs.com/package/sqlite3. This makes a huge difference for large galleries, e.g. 10,000+ photos. From their README:

|   |select 1 row &nbsp;`get()`&nbsp;|select 100 rows &nbsp;&nbsp;`all()`&nbsp;&nbsp;|select 100 rows `iterate()` 1-by-1|insert 1 row `run()`|insert 100 rows in a transaction|
|---|---|---|---|---|---|
|better-sqlite3|1x|1x|1x|1x|1x|
|[sqlite](https://www.npmjs.com/package/sqlite) and [sqlite3](https://www.npmjs.com/package/sqlite3)|8.4x slower|3.7x slower|28.2x slower|3.6x slower|6.0x slower|

**Comment by Crusher00** [comment]
Inline environmental variable did the trick for me on RPi2.

**Comment by Crusher00** [comment]
I only had the problems while installing thumbsup via non. So I did this for installation:
 "LZZ_COMPAT=1 npm  install -g thumbsup" and afterwords I ran thumbsup as normal as stated in the documentation without the need for lzzCompat.

**Comment by rprieto** [comment]
Thank you!
