### ISSUE TITLE
wrong gif thumbnail width and aspect ratio 

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/thumbsup#96]
## Bug report

Thumbnail for animated gif is not square (narrower than other thumbnails by maybe 15%). Proportions
also seems off by same amount (meaning, people look stretched out). 

Running as an npm package:

```
Thumbsup version: 2.2.1
Node version: v9.8.0
NPM version: 5.8.0
Operating system: OS X High Sierra
```

About the bug...

- Are you getting an error message? NO
- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info? Yes. There are no reported problems, but the problematic picture is the only one in its album that is completely skipped in the logs. 
- Is the behavior different from expected? Yes
- Can you provide steps to reproduce the issue? Include an animated gif in an album. Using classic theme.

**Comment by rprieto** [comment]
Hi, thanks for raising the issue. This would be a bug in https://github.com/thumbsup/downsize which is used to create the thumbnails.

This package has a good integration test suite, are you keen to add an animated gif and have a look at the code?

Also, can you confirm you expect the thumbnail to be static? Thumbsup will render the thumbnail with a « play button » overlay when it detects it’s an animated gif.

**Comment by piccolbo** [comment]
I am unable to share the gif that prompted me to create this issue. I took a look at the code and I don't see anything gif-specific. I followed the dependency to gm and there is a smattering of bugs related to gif processing in that project, I think this could be an instance of issue [522](https://github.com/aheckmann/gm/issues/522). I had no expectations concerning the animation of a thumbnail. My only expectations where about the shape (square) and preserving proportions of the original image (which I incorrectly referred to as "aspect ratio", now corrected).

**Comment by piccolbo** [comment]
gm doesn't seem to have had a commit of substance in 2 years. The issue I linked to is also 2 years old. I wouldn't hold my breath.

**Comment by rprieto** [comment]
Hi @piccolbo. I finally got some good results processing GIFs! Creating a non-animated thumbnail works well, with the expected size and proportions preserved.

Thumbsup also creates a "large" of every image, and for that one I can't decide between:

- actually resizing the animated GIF to the desired size (e.g. "maximum height 800px"). I got it working for any GIF & size, but this forces to re-render every frame so the resulting image can be 3 times the size (in Mb)
- simply saying that GIFs don't get resized, because they typically don't need to. Any GIF is simply copied to the output folder as-is.

Do you think one or the other makes more sense, at least in your use case?

**Comment by rprieto** [comment]
After your bug report, I investigated and found that thumbsup doesn’t support animated GIF images at all.

I now have a fix for the thumbnails, but still working on the previews. I know your bug title says “thumbnails” but fixing one without the other doesn’t make sense to me. Thumbsup should either support animated GIFs or not.

If you have an opinion on the question above let me know, otherwise I will make a decision.

**Comment by piccolbo** [comment]
I'd say resize, because 3x size is really not a big deal with gifs and having matching sizes is necessary to the elegance of the gallery. In my opinion, going through  a gallery with sizes all over the place is not pleasant, even if it's just gifs. But I may never make another animated gif again, so don't take my word for it.

**Comment by rprieto** [comment]
Thank you for the feedback! I should have a fix out soon.

**Comment by rprieto** [comment]
Hi @piccolbo, the latest code on master has full support for static & animated GIFs. It will be out with the next minor version.

If you want to process GIF files, there's a new dependency on [Gifsicle](http://www.lcdf.org/gifsicle/) which should be easy to install.

**Comment by piccolbo** [comment]
Great thanks
